on: push
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - run: echo setup
  needs-bare-False:
    needs: setup
    if: False
    runs-on: ubuntu-latest
    steps:
      - run: echo should-skip
  needs-bare-UPPER:
    needs: setup
    if: FALSE
    runs-on: ubuntu-latest
    steps:
      - run: echo should-skip
  needs-bare-True:
    needs: setup
    if: True
    runs-on: ubuntu-latest
    steps:
      - run: echo should-run
  noneeds-bare-False:
    if: False
    runs-on: ubuntu-latest
    steps:
      - run: echo should-skip
  step-bare-False:
    runs-on: ubuntu-latest
    steps:
      - if: False
        run: echo step-should-skip
      - run: echo after
