name: c
on: push
jobs:
  deep:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cfg:
          - {l1: {l2: {l3: {l4: deepest}}}, arr: [{in: obj}, [nested, list]]}
    steps:
      - run: "true"
  long:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cfg:
          - {a: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa, b: bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb, c: cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc, d: dddddddddddddddddddddddddddddddddddddddddddd}
    steps:
      - run: "true"
