name: e1-include
on: push
jobs:
  incorder:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [a]
        arch: [x]
        include:
          - {zz: z1, arch: q, os: c, aa: a1}
          - {arch: q2, other: o2}
          - {os: c3}
    steps:
      - run: "true"
  docs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        fruit: [apple, pear]
        animal: [cat, dog]
        include:
          - color: green
          - color: pink
            animal: cat
          - fruit: apple
            shape: circle
          - fruit: banana
          - animal: cow
            fruit: kiwi
    steps:
      - run: "true"
