name: e4-json
on: push
jobs:
  jsonvector:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        v: ${{ fromJSON('[{"b":1,"a":2,"c":{"z":"zz","y":"yy"}}]') }}
    steps:
      - run: "true"
  jsonmatrix:
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJSON('{"zeta":["z"],"alpha":["a"],"include":[{"zeta":"n","q":"qq","b":"bb"}]}') }}
    steps:
      - run: "true"
  jsonnums:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        v: ${{ fromJSON('[1.0, 1e3, 12345678901234567890, true, null, ""]') }}
    steps:
      - run: "true"
