name: e5-truncate
on: push
jobs:
  multibyte:
    name: ééééééééééééééééééééééééééééééééééééééééééééééééééxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    runs-on: ubuntu-latest
    steps:
      - run: "true"
  surrogate:
    name: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx😀yyyyyyyy
    runs-on: ubuntu-latest
    steps:
      - run: "true"
  exact100:
    name: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    runs-on: ubuntu-latest
    steps:
      - run: "true"
  exact101:
    name: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxy
    runs-on: ubuntu-latest
    steps:
      - run: "true"
  exprlong:
    name: ${{ format('{0}{0}{0}{0}{0}{0}{0}{0}{0}{0}{0}', 'abcdefghij') }}
    runs-on: ubuntu-latest
    steps:
      - run: "true"
