name: e6-reusable
on: push
jobs:
  call:
    strategy:
      matrix:
        v: [{k: one}, {k: two}]
    uses: ./.github/workflows/r.yml
  callnamed:
    name: Named Caller
    strategy:
      matrix:
        v: [p]
    uses: ./.github/workflows/r.yml
