name: log-commands
on:
  workflow_dispatch:
  push:
    branches: [log-commands]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: v2 form
        run: |
          echo "--- begin ---"
          echo "::error::bracket%5Dhere semi%3Bhere pct%25here"
          echo "::group::grp%5Dhere semi%3Bhere"
          echo "::endgroup::"
          echo "::error::colon%3Ahere comma%2Chere"
          echo "--- end ---"
