{
  "name": "probe-empty-axis",
  "on": {
    "push": {
      "branches": [
        "matrix-names"
      ]
    }
  },
  "jobs": {
    "empty_axis": {
      "name": "${{ format('empty_axis:{0}', toJSON(matrix)) }}",
      "runs-on": "ubuntu-latest",
      "strategy": {
        "matrix": {
          "v": []
        }
      },
      "steps": [
        {
          "run": "true"
        }
      ]
    }
  }
}
