{
  "name": "probe-exclude-type",
  "on": {
    "push": {
      "branches": [
        "matrix-names"
      ]
    }
  },
  "jobs": {
    "exclude_type": {
      "runs-on": "ubuntu-latest",
      "strategy": {
        "matrix": {
          "v": [
            1,
            "1",
            true
          ],
          "exclude": [
            {
              "v": "1"
            }
          ]
        }
      },
      "steps": [
        {
          "run": "true"
        }
      ]
    }
  }
}
