{
  "name": "probe-reusable",
  "on": {
    "workflow_call": {}
  },
  "jobs": {
    "plain": {
      "name": "IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII",
      "runs-on": "ubuntu-latest",
      "strategy": {
        "matrix": {
          "v": [
            "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYY"
          ]
        }
      },
      "steps": [
        {
          "run": "true"
        }
      ]
    },
    "expression": {
      "name": "${{ format('{0}', matrix.v) }}",
      "runs-on": "ubuntu-latest",
      "strategy": {
        "matrix": {
          "v": [
            "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ"
          ]
        }
      },
      "steps": [
        {
          "run": "true"
        }
      ]
    }
  }
}
