name: release-tag

on:
  push:
    tags:
      - "v[0-9]*"
      - "!v[0-9]*-*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - run: git fetch --unshallow --quiet --tags --force
      - env:
          GITHUB_TOKEN: ${{ github.token }}
          TAG: ${{ github.ref_name }}
        run: |
          git tag --list "$TAG" --format='%(contents:body)' > release.notes
          gh release create "$TAG" --title "$TAG" --notes-file release.notes
